---
- name: Display Ansible version
  ansible.builtin.debug:
    msg: "Ansible version is  {{ ansible_version.full }}"

- name: Install sudo
  ansible.builtin.yum:
    name: sudo
    state: present

- name: "Retrieve assets server from env"
  ansible.builtin.set_fact:
    assets_server: "{{ lookup('env','MIDDLEWARE_DOWNLOAD_RELEASE_SERVER_URL') }}"

- name: "Change service name if running with jws."
  ansible.builtin.set_fact:
    jws_service_name: jws5-tomcat

- name: "Download and deploy jws zips from {{ assets_server }}"
  ansible.builtin.get_url:
    url: "{{ asset }}"
    dest: "/opt"
    validate_certs: no
  loop: "{{ jws_molecule_assets }}"
  loop_control:
    loop_var: asset
  when:
    - assets_server is defined
    - assets_server | length > 0
