---
# The following is only for upstream: if jws_version is not defined
# we use the latest version of Apache Tomcat
- name: "Set default values"
  ansible.builtin.set_fact:
    zipfile_name: "apache-tomcat-{{ tomcat_version }}.zip"
    zipfile_url: "{{ jws_apache_archive_download_url_prefix }}{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.zip"
  when:
    - not jws_version is defined

- name: "Check that jws_home has been defined."
  ansible.builtin.assert:
    that:
      - jws_home is defined
      - jws_home | length > 0

- name: "Include tasks for Java installation (if Java version is provided)"
  ansible.builtin.include_tasks: java_install.yml
  when:
    - jws_java_version is defined

- name: "Perform setup"
  when:
    - jws_setup is defined
    - jws_setup
  block:
    - name: "Check state of install_dir: {{ jws_install_dir }}"
      ansible.windows.win_stat:
        path: "{{ jws_install_dir }}"
      register: install_path

    - name: "Ensure install dir is created: {{ jws_install_dir }}"
      ansible.windows.win_file:
        path: "{{ jws_install_dir }}"
        state: directory
      when:
        - not install_path.stat.exists

    - name: "Set defaults values based on facts (if values not provided)"
      ansible.builtin.include_tasks: defaults.yml

    - name: "Include install tasks"
      ansible.builtin.include_tasks: install.yml


    - name: "Ensure {{ jws_home }} folders have appropriate permissions"
      ansible.windows.win_acl:
        path: "{{ jws_home }}"
        user: "LOCAL SERVICE"
        rights: FullControl
        state: present
        type: allow

- name: "Start Tomcat"
  ansible.windows.win_command:
    cmd: 'net start tomcat9'
