---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - package_name is defined
    quiet: true

- name: "Install package"
  ansible.builtin.yum:
      name: "{{ package_name }}"
      state: installed
