---
name: CI
on:
  push:
    branches:
      - fix_workflows_and_various_inconsistencies
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@fix_workflows_and_various_inconsistencies
    secrets: inherit
    with:
      fqcn: 'middleware_automation/jws'
      molecule_tests: >-
        [ "default", "ajp_or_https", "force_install", "override_server_xml", "preinstalledjdk", "uninstall" ]
